DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
	id SERIAL PRIMARY KEY,
	type_id INTEGER NOT NULL,
	size INTEGER NOT NULL,
	is_buy BOOLEAN NOT NULL,
	fulfilled INTEGER NOT NULL,
	price DOUBLE PRECISION NOT NULL,
	client_id INTEGER NOT NULL,
	ric_id INTEGER NOT NULL	
);
